local iction = iction
iction.ictSpellsListFrameData = {
                                uiName = "ictionSpellsList",
                                nameAttr = "ictionSpellsList",
                                uiInherits = nil,
                                userPlaced = false,
                                movable = false,
                                enableMouse = false,
                                SetClampedToScreen = false,
                                uiInherits = "InsetFrameTemplate",
                                w = 150,
                                h = 400,
                                bgCol = {r = 1, g = 0, b= 0, a = 0},
                                strata = "MEDIUM",
                                pointPosition = {point = "CENTER",
                                                 relativeTo = nil,
                                                 relativePoint = "CENTER",
                                                 x = 0, y = 0},
                                textures = { [1] = {name = "iction_SpellsListBG",
                                                    allPoints = true,
                                                    level = "ARTWORK",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 0.5, vg = 0.5, vb = 0.5, va = 0.0 } },
                                }