local iction = iction
iction.ictSpellsListFrameData = {
                                uiName = "ictionSpellsList",
                                nameAttr = "ictionSpellsList",
                                uiInherits = nil,
                                userPlaced = false,
                                movable = false,
                                enableMouse = false,
                                SetClampedToScreen = false,
                                uiInherits = "UIPanelScrollFrameTemplate",
                                w = 250,
                                h = 250,
                                bgCol = {r = 1, g = 0, b= 0, a = 0},
                                strata = "MEDIUM",
                                pointPosition = {point = "LEFT",
                                                 relativeTo = nil,
                                                 relativePoint = "RIGHT",
                                                 x = 5, y = 0},
                                textures = { [1] = {name = "iction_SpellsListBG",
                                                    allPoints = true,
                                                    level = "ARTWORK",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 0.5, vg = 0.1, vb = 0.1, va = 0.85  } },
                                }