local iction = iction
iction.ictArtifactFrameData = { uiType = "Button",
                                uiName = "iction_artifactFrame",
                                nameAttr = "Artifact",
                                uiInherits = nil,
                                userPlaced = true,
                                movable = true,
                                enableMouse = false,
                                SetClampedToScreen = true,
                                w = iction.bw,
                                h = iction.bh,
                                bgCol = {r = 0, g = 0, b= 0, a = 0},
                                strata = "LOW",
                                pointPosition = {point = "BOTTOM",
                                                 relativeTo = nil,
                                                 relativePoint = "CENTER",
                                                 x = 2, y = 5},
                                textures = { [1] = {name = "ARTIFACTMOVEFRAME", allPoints = true, level = "ARTWORK",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 1, vg = 1, vb = 1, va = 0} },
                                }