local iction = iction
iction.ictBuffFrameData = { uiType = "Frame",
                            uiName = "iction_buffFrame",
                            nameAttr = "Buff",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 128,
                            h = 32,
                            bgCol = {r = 1, g = 1, b= 0, a = 1},
                            strata = "HIGH",
                            texture = {name = nil, allPoints = true, level = "ARTWORK",
                                       texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                       vr = 1, vg = 1, vb = 1, va = .25},
                            pointPosition = {point = "CENTER",
                                             relativeTo = nil,
                                             relativePoint = "CENTER",
                                             x = 0, y = 0},
                            }
