local iction = iction
iction.ictBuffFrameData = { uiType = "Frame",
                            uiName = "iction_buffFrame",
                            nameAttr = "Buff",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 128,
                            h = 32,
                            bgCol = {r = 1, g = 1, b= 0, a = 0},
                            strata = "LOW",
                            pointPosition = {point = "CENTER",
                                             relativeTo = nil,
                                             relativePoint = "CENTER",
                                             x = 0, y = 0},
                            textures = { [1] = {name = nil, allPoints = true, level = "ARTWORK",
                                                texture = "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = 0} },
                          }