local iction = iction
iction.ictConflagData = { uiType = "Frame",
                            uiName = "iction_conflagFrame",
                            nameAttr = "iction_conflagFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 128,
                            h = 32,
                            bgCol = {r = 0, g = 1, b = 0, a = 0},
                            strata = "MEDIUM",
                            pointPosition = {point = "BOTTOM",
                                 relativeTo = nil,
                                 relativePoint = "CENTER",
                                 x = 0, y = 80},
                            textures = { [1] = {name = "default", allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = 0},
                                         [2] = {name = "conflag-01",
                                                allPoints = false,
                                                anchorPoint = "LEFT",
                                                apX = 15,
                                                apY = 0,
                                                w = 15,
                                                h= 15,
                                                level = "ARTWORK",
                                                texture= "Interface/AddOns/iction/media/icons/conflag",
                                                vr = 1, vg = 1, vb = 1, va = 0},
                                         [3] = {name = "conflag-02",
                                                allPoints = false,
                                                anchorPoint = "LEFT",
                                                apX = 30,
                                                apY = 0,
                                                w = 15,
                                                h= 15,
                                                level = "ARTWORK",
                                                texture= "Interface/AddOns/iction/media/icons/conflag",
                                                vr = 1, vg = 1, vb = 1, va = 0} },
                            }