iction.ictDeBuffColumnData = { uiType = "Frame",
                                uiName = "tmp",
                                nameAttr = "tmp",
                                uiInherits = nil,
                                userPlaced = true,
                                movable = true,
                                enableMouse = false,
                                SetClampedToScreen = true,
                                w = iction.bw+5,
                                h = iction.bh+5,
                                bgCol = {r = 0, g = 1, b= 0, a = 1},
                                strata = "BACKGROUND",
                                texture = {name = nil, allPoints = true, level = "ARTWORK",
                                           texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                           vr = 1, vg = 1, vb = 1, va = 0},
                                point = {pos = "BOTTOM", x = -2, y = 5},
                                }
