local iction = iction
iction.ictHighLightFrameData = { uiType = "Frame",
                                uiName = "iction_highlightFrame",
                                nameAttr = "iction_highlightFrame",
                                uiInherits = nil,
                                userPlaced = true,
                                movable = true,
                                enableMouse = false,
                                SetClampedToScreen = true,
                                w = 128,
                                h = 32,
                                bgCol = {r = 0, g = 1, b= 0, a = 0},
                                strata = "BACKGROUND",
                            textures = { [0] = nil,
                                         [1] = {name = nil, allPoints = true, level = "BACKGROUND",
                                           texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                           vr = 1, vg = 1, vb = 1, va = 0.5 }
                                           },
                                pointPosition = {point = "CENTER",
                                 relativeTo = nil,
                                 relativePoint = "CENTER",
                                 x = 0, y = 0},
                                }