local iction = iction
iction.ictHighLightFrameData = { uiType = "Frame",
                                uiName = "iction_highlightFrame",
                                nameAttr = "iction_highlightFrame",
                                uiInherits = nil,
                                userPlaced = true,
                                movable = true,
                                enableMouse = false,
                                SetClampedToScreen = true,
                                w = iction.bw,
                                h = iction.bh,
                                bgCol = {r = 0, g = 1, b= 0, a = 0},
                                strata = "BACKGROUND",
                                pointPosition = {point = "CENTER",
                                                 relativeTo = nil,
                                                 relativePoint = "CENTER",
                                                 x = 0, y = 0},
                                textures = { [1] = {name = 'default', allPoints = true, level = "BACKGROUND",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 1, vg = 1, vb = 1, va = 0 },
                                             [2] = {name = "ict_highlightTexture",
                                                    allPoints = true,
                                                    anchorPoint = "CENTER",
                                                    apX = 0,
                                                    apY = 0,
                                                    w = 24,
                                                    h= 24,
                                                    level = "ARTWORK",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 1, vg = 1, vb = 1, va = 0}}
                                }