iction.ictHighLightFrameData = { uiType = "Frame",
                            uiName = "iction_highlightFrame",
                            nameAttr = "iction_highlightFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 128,
                            h = 32,
                            bgCol = {r = 0, g = 1, b= 0, a = 0},
                            strata = "HIGH",
                            texture = {name = nil, allPoints = true, level = "ARTWORK",
                                       texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                       vr = 1, vg = 1, vb = 1, va = 0},
                            point = {pos = "CENTER", x = 0, y = 0},
                            }