iction.ictInsanityData = {  uiType = "Frame",
                            uiName = "iction_insanityFrame",
                            nameAttr = "iction_insanityFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 100,
                            h = iction.bh/2,
                            bgCol = {r = 0, g = 1, b= 0, a = .5},
                            strata = "MEDIUM",
                            texture = {name = "insanityMOVEFRAME", allPoints = true, level = "ARTWORK",
                                       texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                       vr = 1, vg = 1, vb = 1, va = .1},
                            point = {pos = "BOTTOM", x = 0, y = 80},
                            }