local iction = iction
iction.ictInsanityData = {  uiType = "Frame",
                            uiName = "iction_insanityFrame",
                            nameAttr = "iction_insanityFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 100,
                            h = iction.bh/2,
                            bgCol = {r = 0, g = 1, b= 0, a = .5},
                            strata = "MEDIUM",
                            pointPosition = {point = "BOTTOM",
                                             relativeTo = nil,
                                             relativePoint = "CENTER",
                                             x = 0, y = 80},
                            textures = { [1] = {name = "insanityMOVEFRAME", allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = .1 },
                                          [2] = { name = "insanity",
                                                allPoints = false,
                                                anchorPoint = "LEFT",
                                                apX = -3,
                                                apY = 0,
                                                w = 106,
                                                h= iction.bh/1.8,
                                                level = "BACKGROUND",
                                                texture= "Interface/AddOns/iction/media/icons/soulShard",
                                                vr = 0, vg = 0, vb = 0, va = 1},
                                          [3] = { name = "insanity2",
                                                allPoints = false,
                                                anchorPoint = "LEFT",
                                                apX = 0,
                                                apY = 0,
                                                w = 1,
                                                h= iction.bh/2,
                                                level = "BACKGROUND",
                                                texture= "Interface/AddOns/iction/media/icons/soulShard",
                                                vr = 0.5, vg = 0.1, vb = 1, va = 1 }
                                        }
                            }
