local iction = iction
iction.ictOptionsFrameData = { uiType = "Frame",
                            uiName = "ictionOptions",
                            nameAttr = "ictionOptions",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = true,
                            SetClampedToScreen = true,
                            uiInherits = "ThinBorderTemplate",
                            w = 600,
                            h = 380,
                            bgCol = {r = 1, g = 0, b= 0, a = 1},
                            strata = "MEDIUM",
                            pointPosition = {point = "CENTER",
                                             relativeTo = UIParent,
                                             relativePoint = "CENTER",
                                             x = 0, y = 150},
                            textures = { [1] = {name = "iction_OptionsBG",
                                                allPoints = true,
                                                level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 0.4, vg = 0.1, vb = 0.1, va = 0.85 } },
                            }