local iction = iction
iction.ictSkinListFrameData = {
                                uiName = "ictionSkinCheckBoxList",
                                nameAttr = "ictionSkinCheckBoxList",
                                uiInherits = nil,
                                userPlaced = false,
                                movable = false,
                                enableMouse = false,
                                SetClampedToScreen = false,
                                uiInherits = "UIPanelScrollFrameTemplate",
                                w = 100,
                                h = 110,
                                bgCol = {r = 1, g = 0, b= 0, a = 0},
                                strata = "MEDIUM",
                                pointPosition = {point = "LEFT",
                                                 relativeTo = nil,
                                                 relativePoint = "RIGHT",
                                                 x = 30, y = 0},
                                textures = { [1] = {name = "ictionSkinCheckBoxListBG",
                                                    allPoints = true,
                                                    level = "ARTWORK",
                                                    texture= "",
                                                    vr = 0.4, vg = 0.5, vb = 0.1, va = 0.85  } },
                                }