local iction = iction
iction.ictColumnCheckBoxListFrameData = {
                                uiName = iction.L['maxTargetColsLabel'],
                                nameAttr = "ictionColumnCheckBoxList",
                                uiInherits = nil,
                                userPlaced = false,
                                movable = false,
                                enableMouse = false,
                                SetClampedToScreen = false,
                                uiInherits = "UIPanelScrollFrameTemplate",
                                w = 150,
                                h = 145,
                                bgCol = {r = 1, g = 0, b= 0, a = 1},
                                strata = "MEDIUM",
                                pointPosition = {point = "RIGHT",
                                                 relativeTo = nil,
                                                 relativePoint = "LEFT",
                                                 x = 0, y = 0},
                                textures = { [1] = {name = "ictionColumnCheckBoxListBG",
                                                    allPoints = true,
                                                    level = "ARTWORK",
                                                    texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                    vr = 0.4, vg = 0.5, vb = 0.1, va = 0.85  } },
                                }