local iction = iction
iction.ictShardData = { uiType = "Frame",
                        uiName = "iction_shardFrame",
                        nameAttr = "iction_shardFrame",
                        uiInherits = nil,
                        userPlaced = true,
                        movable = true,
                        enableMouse = false,
                        SetClampedToScreen = true,
                        w = 128,
                        h = 32,
                        bgCol = {r = 0, g = 1, b= 0, a = 0},
                        strata = "MEDIUM",
                        textures = { [0] = nil,
                                    [1] = {name = "shard-01",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 5,
                                        apY = 0,
                                        w = 32,
                                        h= 22,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/icons/soulShard",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                    [2] = {name = "shard-02",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 28,
                                        apY = 3,
                                        w = 32,
                                        h= 28,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/icons/soulShard",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                    [3] = {name = "shard-03",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 51,
                                        apY = 5,
                                        w = 32,
                                        h= 32,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/icons/soulShard",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                    [4] = {name = "shard-04",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 74,
                                        apY = 7,
                                        w = 32,
                                        h= 36,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/icons/soulShard",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                    [5] = {name = "shard-05",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 95,
                                        apY = 9,
                                        w = 32,
                                        h= 42,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/icons/soulShard",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                    },
                        pointPosition = {point = "CENTER",
                                 relativeTo = nil,
                                 relativePoint = "CENTER",
                                 x = 0, y = 50},
                        }