iction.skinData = {}
iction.skin01Data = {
                    {uiType = "Frame",
                    uiName = "iction_bg1",
                    nameAttr = "iction_bg1",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    texture = {name = nil, allPoints = true, level = "ARTWORK",
                               texture= "Interface/AddOns/iction/media/bg/bg1",
                               vr = 1, vg = 1, vb = 1, va = 1},
                    point = {pos = "CENTER", x = -96, y = 0 }
                    },

                    {uiType = "Frame",
                    uiName = "iction_bg2",
                    uiParentFrame = nil,
                    nameAttr = "iction_bg2",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    texture = {name = nil, allPoints = true, level = "ARTWORK",
                               texture= "Interface/AddOns/iction/media/bg/bg2",
                               vr = 1, vg = 1, vb = 1, va = 1},
                    point = {pos = "CENTER", p = nil, x = -32, y = 0}
                    },

                    {uiType = "Frame",
                    uiName = "iction_bg3",
                    uiParentFrame = nil,
                    nameAttr = "iction_bg3",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    texture = {name = nil, allPoints = true, level = "ARTWORK",
                               texture= "Interface/AddOns/iction/media/bg/bg3",
                               vr = 1, vg = 1, vb = 1, va = 1},
                    point = {pos = "CENTER", p = nil, x = 32, y = 0 }
                    },

                    {uiType = "Frame",
                    uiName = "iction_bg4",
                    uiParentFrame = nil,
                    nameAttr = "iction_bg4",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    texture = {name = nil, allPoints = true, level = "ARTWORK",
                               texture= "Interface/AddOns/iction/media/bg/bg4",
                               vr = 1, vg = 1, vb = 1, va = 1},
                    point = {pos = "CENTER", p = nil, x = 96, y = 0}
                    }
}
table.insert(iction.skinData, iction.skin01Data)