iction.skinData = {}
iction.skin01Data = {
                    {uiType = "Frame",
                    uiName = "iction_bg1",
                    nameAttr = "iction_bg1",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    pointPosition = {point =  "CENTER", relativeTo = nil, relativePoint = "CENTER", x = 0, y = 0 },
                    textures = { [1] = {name = "default", allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = 0},
                                 [2] = {name = "skin01_1",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/bg1",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [3] = {name = "skin01_2",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/bg2",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [4] = {name = "skin01_3",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/bg3",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [5] = {name = "skin01_4",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/bg4",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                }
                    }
}
table.insert(iction.skinData, iction.skin01Data)

iction.skin02Data = {
                    uiType = "Frame",
                    uiName = "iction_bg1",
                    nameAttr = "iction_bg1",
                    uiInherits = nil,
                    userPlaced = false,
                    movable = false,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 128,
                    h = 128,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    pointPosition = {point =  "CENTER", relativeTo = nil, relativePoint = "CENTER", x = 0, y = 0},
                    textures = { [1] = {name = "default", allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = 0},
                                 [2] = {name = "skin02_1",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin02_1",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [3] = {name = "skin02_2",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin02_2",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [4] = {name = "skin02_3",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin02_3",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [5] = {name = "skin02_4",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin02_4",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                }
                    }
table.insert(iction.skinData, iction.skin02Data)

iction.skin03Data = {
                    {uiType = "Frame",
                    uiName = "iction_bg1",
                    nameAttr = "iction_bg1",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 64,
                    h = 64,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    pointPosition = {point =  "CENTER", relativeTo = nil, relativePoint = "CENTER", x = -96, y = 0 },
                    textures = { [1] = {name = "default", allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 1, vg = 1, vb = 1, va = 0},
                                 [2] = {name = "skin03_1",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin03_1",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [3] = {name = "skin03_2",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = -32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin03_2",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [4] = {name = "skin03_3",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 32,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin03_3",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                 [5] = {name = "skin03_4",
                                        allPoints = false,
                                        anchorPoint = "LEFT",
                                        apX = 96,
                                        apY = 0,
                                        w = 64,
                                        h= 64,
                                        level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin03_4",
                                        vr = 1, vg = 1, vb = 1, va = 1},
                                }
                    },
}
table.insert(iction.skinData, iction.skin03Data)

iction.skin04Data = {
                    {uiType = "Frame",
                    uiName = "iction_bg4",
                    nameAttr = "iction_bg4",
                    uiInherits = nil,
                    userPlaced = true,
                    movable = true,
                    enableMouse = false,
                    SetClampedToScreen = true,
                    w = 128,
                    h = 128,
                    bgCol = {r = 0, g = 1, b= 0, a = 0},
                    strata = "BACKGROUND",
                    textures = {
                                 [1] = {name = "skin04_1", allPoints = true, level = "ARTWORK",
                                        texture= "Interface/AddOns/iction/media/bg/skin04",
                                        vr = 1, vg = 1, vb = 1, va = 1 }
                    },
                    pointPosition = {point =  "CENTER", relativeTo = nil, relativePoint = "CENTER", x = 0, y = 0}
                    },
}
table.insert(iction.skinData, iction.skin04Data)