local iction = iction
iction.ictSpellFrameData = {
                            uiName = nil,
                            nameAttr = "ictionDeBuffFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = false,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 1,
                            h = 1,
                            bgCol = {r = 0, g = 0, b= 0, a = 0},
                            strata = "BACKGROUND",
                            pointPosition = {point = "BOTTOM",
                                             relativeTo = nil,
                                             relativePoint = "CENTER",
                                             x = 0, y = -20},
                            textures = { [1] = {name = 'default', allPoints = true, level = "BACKGROUND",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 0, vg = 0, vb = 0, va = 1 } },
                            }
