local iction = iction
iction.ictSpellFrameData = { uiType = "Frame",
                            uiName = nil,
                            nameAttr = "ictionDeBuffFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = false,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 1,
                            h = 1,
                            bgCol = {r = 0, g = 0, b= 0, a = 0},
                            strata = "HIGH",
                            textures = { [0] = nil,
                                         [1] = {name = nil, allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 0, vg = 0, vb = 0, va = 0 }
                            },
                            pointPosition = {point = "BOTTOM",
                                     relativeTo = nil,
                                     relativePoint = "CENTER",
                                     x = 0, y = -20},
                            }
