iction.ictStackFrameData = { uiType = "Frame",
                            uiName = nil,
                            nameAttr = "ictionStackFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 1,
                            h = 1,
                            bgCol = {r = 0, g = 0, b= 0, a = 0},
                            strata = "MEDIUM",
                            texture = {name = nil, allPoints = true, level = "ARTWORK",
                                       texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                       vr = 0, vg = 0, vb = 0, va = 1},
                            point = {pos = "TOP", x = 20, y = 10},
                            }
