local iction = iction
iction.ictStackFrameData = { uiType = "Frame",
                            uiName = nil,
                            nameAttr = "ictionStackFrame",
                            uiInherits = nil,
                            userPlaced = true,
                            movable = true,
                            enableMouse = false,
                            SetClampedToScreen = true,
                            w = 1,
                            h = 1,
                            bgCol = {r = 0, g = 0, b= 0, a = 0},
                            strata = "MEDIUM",
                            pointPosition = {point = "TOP",
                                             relativeTo = nil,
                                             relativePoint = "CENTER",
                                             x = 20, y = 10},
                            textures = { [1] = {name = 'default', allPoints = true, level = "ARTWORK",
                                                texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                                vr = 0, vg = 0, vb = 0, va = 1 } },
                            }
