local iction = iction
iction.ictSWDData = {  uiType = "Frame",
                        uiName = "iction_SWDFrame",
                        nameAttr = "iction_SWDFrame",
                        uiInherits = nil,
                        userPlaced = true,
                        movable = true,
                        enableMouse = false,
                        SetClampedToScreen = true,
                        w = iction.bw*2,
                        h = iction.bh*2,
                        bgCol = {r = 0, g = 0, b= 0, a = 0},
                        strata = "MEDIUM",
                        pointPosition = {point = "BOTTOM",
                                         relativeTo = nil,
                                         relativePoint = "CENTER",
                                         x = 0, y = 80},
                        textures = { [1] = {name = "SWDMOVEFRAME", allPoints = true, level = "ARTWORK",
                                            texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                            vr = 1, vg = 1, vb = 1, va = 0 },
                                     [2] = {name = "ict_SWDTexture",
                                            allPoints = true,
                                            anchorPoint = "LEFT",
                                            level = "BACKGROUND",
                                            apX = 0,
                                            apY = 0,
                                            w = 15,
                                            h= 15,
                                            texture= "Interface/AddOns/iction/media/icons/soulShard",
                                            vr = 1, vg = 1, vb = 1, va = 1},
                                    },
                     }
