local iction = iction
iction.ictVoidData = {  uiType = "Frame",
                        uiName = "iction_voidFrame",
                        nameAttr = "iction_voidFrame",
                        uiInherits = nil,
                        userPlaced = true,
                        movable = true,
                        enableMouse = false,
                        SetClampedToScreen = true,
                        w = iction.bw*1.25,
                        h = iction.bh*1.25,
                        bgCol = {r = 0, g = 0, b= 0, a = 0},
                        strata = "MEDIUM",
                        scale = iction.VoidboltScale,
                        pointPosition = {point = "BOTTOM",
                                         relativeTo = nil,
                                         relativePoint = "CENTER",
                                         x = 0, y = 80},
                        textures = {[1] = {name = "VOIDMOVEFRAME", allPoints = true, level = "ARTWORK",
                                           texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                           vr = 1, vg = 1, vb = 1, va = 0 },
                                    [2] = { name = "ict_voidFrameTexture",
                                            allPoints = true,
                                            anchorPoint = "CENTER",
                                            apX = 5,
                                            apY = 0,
                                            w = 15,
                                            h= 15,
                                            level = "ARTWORK",
                                            texture= "Interface\\ChatFrame\\ChatFrameBackground",
                                            vr = 1, vg = 1, vb = 1, va = 0}}
                    }